twig:
    default_path: '%kernel.project_dir%/templates'
    #debug: '%kernel.debug%'
    #exception_controller: null
    form_themes: 
        - '@OlixBackOffice/Twig/form-theme-horizontal-layout.html.twig'
        - '_form/custom_types.html.twig'
    globals:
        uri_recipe: '%recipe_path%'
        uri_category: '%category_path%'

when@test:
    twig:
        strict_variables: true
